travis:
  secure:
    BINSTAR_TOKEN: leqYsLHk1X6MngPheLnJC9b/5y2bHp7v2OqWpTfo0EB8PSmYNaxGyyslpDYMFFdGEGSksf7oVGij3DWczQmFz9p1+5/RMT5FUAvu9WN0BXK715k6o46bswq1tE9iaBvgjh4dFfI/FXo0bsOhgltgcEkweOGVWHuap9MDUcHtyX4o0bRqUMrdvYVwQwmuGbPaqRLQZi7F0hKS93UUb3x6jmciYrtz8ud+ufveCiK3dyZVFbj08W0kplJfJ2v/LgWEf03hOeGmDxCrAl6M6YnRC+hFi5IVIlShNjtIyvSV48YgRXZjqsDzYYi9ARCRAXHzu5GNhfDxLqzbHn0Q7wb3oo8rlfSXIjB3lQZikaFDvIiWgXgVRKLJ9pNVgRHdwBhl8AEIk1VH8hFlefMtdSPyz62H2Ugs4r8VMtSFCr8KFt6ESdwxHtswHDpj86QLAg2R03x59EP7cn4SxUvOdSLqxrM6V4Y0YbmKtVgF/t/pdriW3FclC+zUrQqcF0W05sJbwmgpXo7LURyQaE1xFLNHbuqV+aXNCFDQokZMZHFLg86CutzvSV+9BmcF3jNbaDO9br9GoCCE1qwA7b9hgdPCqMwBbsFZGO5IceL/+Oadp9S4Q8WKIvtQMGmbEvwzurJds24qVS3kexGlpPU1sKQjK+k0WIPWWR+hMwkm1f2hlZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
